package hyperface.cms.model.enums;

enum TransactionType {
    AUTHORIZATION_REVERSAL,
    AUTHORIZE,
    CASHBACK,
    CASHBACK_REVERSAL,
    EMI,
    FEE,
    FEE_REVERSAL,
    INTEREST,
    INTEREST_REVERSAL,
    REFUND,
    REFUND_REVERSAL,
    REMITTANCE,
    REMITTANCE_REVERSAL,
    REPAYMENT,
    REPAYMENT_REVERSAL,
    SETTLEMENT_CREDIT,
    SETTLEMENT_CREDIT_CASH,
    SETTLEMENT_DEBIT,
    SETTLEMENT_DEBIT_CASH,
    SURCHARGE,
    SURCHARGE_REVERSAL,
    TAX,
    TAX_REVERSAL;
}
